### PR TITLE
Add issuer icon for GreenAddress

### PR DESCRIPTION
**Pull request by yegortimoshenko**
This patch adds iconset for GreenAddress. I didn't test it and I didn't update `IssuerIcons.sketch` though, since I don't really know how to use Xcode and I don't even have it installed.

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Hey @yegortimoshenko, thanks for contributing! I'll try this out locally and make any necessary adjustments when I have some time over.

**Comment by calleerlandsson** [comment]
Hey @yegortimoshenko, thanks for working on this. I made some small tweaks and merged this as 6a3944648d15312d642f0d50b12aefe105b809c9.

**Comment by calleerlandsson** [comment]
I'll push out a new TestFlight version now and also submit version 1.1 to Apple.

**Comment by yegortimoshenko** [comment]
Thank you!

**Pull request closed without merging**
