### PR TITLE
Add icons for Microsoft, Linode and Hover

### PR DESCRIPTION
**Pull request by iKenndac**
This PR adds icons for Microsoft, Linode and Hover.

Note: This _hasn't _ been tested on my device with my data since Xcode got bitchy about Code Signing, and I wondered if changing the certificate would do something to Keychain data.

### CODE REVIEW

**Comment by iKenndac** [comment]
simulator screen shot 17 mar 2016 09 10 51

**Comment by calleerlandsson** [comment]
This looks great, @iKenndac! Thanks so much for contributing!

Unfortunately, I've come down with a cold and have quite a fever. I will try this out on my device, merge and push out a new build as soon as I feel a bit better.

**Comment by iKenndac** [comment]
Get well soon! :+1:

**Comment by calleerlandsson** [comment]
Hey @iKenndac! I just tried this on my device and it looks and works great! I'll merge this and push a build to TestFlight.

**Pull request merged**
