### PR TITLE
Add Mastodon icon

### PR DESCRIPTION
**Pull request by FIGBERT**
Because Mastodon has no centralized provider, the issuer will have to be manually set to "Mastodon." I am planning on submitting further PRs and issues related to provider detections.

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Thanks @FIGBERT, this icon also looks great! Do you think we could make the same changes to this PR we discussed regarding #50?

**Comment by FIGBERT** [comment]
@calleerlandsson Now this PR should match #50!

**Comment by calleerlandsson** [comment]
Hey @FIGBERT, after merging #50, `IssuerIcons.sketch` is now in conflict. I guess this would be avoided by both of our ides in #52?

**Comment by calleerlandsson** [comment]
Hey @FIGBERT, would you mind adding this as a PNG to `IssuerIcons/` instead without rounded corners. Also, feel free to add a larger size (I've been using 1024x1024) as this gives us some flexibility if we end up wanting to show icons in a larger size. Thanks!

**Comment by FIGBERT** [comment]
I'll submit a revised PR in a couple hours for the new format.

**Comment by FIGBERT** [comment]
Updated and mergeable!

**Comment by calleerlandsson** [comment]
Excellent, thank you! 🎉

**Pull request merged**
