### PR TITLE
Add six new issuer icons

### PR DESCRIPTION
**Pull request by danbee**
* Adobe ID
* Backblaze
* Coinbase
* Kickstarter
* Name.com
* Privacy

I've been able to test all of these except Name.com.

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Hey @danbee, thanks for the PR! The icons looks great. I'll push them out in a Tesflight build today.

**Comment by danbee** [comment]
Sweet! Can you remind me how I access the Testflight build?

**Comment by calleerlandsson** [comment]
Sorry, I thought you were already invited to TestFlight! I've sent an invitation to your email address now. It should also contain instructions for how to download the build.

**Comment by danbee** [comment]
No worries! I think I was at some point but I have since upgraded my phone and it didn't seem to transfer across. I just followed the link and the new build looks great! So nice to see all the icons present now.

**Comment by calleerlandsson** [comment]
Nice! I've sent the build for App Store review so it should be released within a few days.

**Pull request merged**
